asesores:
    path:     /
    defaults: { _controller: "TGUdecBundle:Asesores:index" }

asesores_show:
    path:     /{id}/show
    defaults: { _controller: "TGUdecBundle:Asesores:show" }

asesores_new:
    path:     /new
    defaults: { _controller: "TGUdecBundle:Asesores:new" }

asesores_create:
    path:     /create
    defaults: { _controller: "TGUdecBundle:Asesores:create" }
    requirements: { _method: post }

asesores_edit:
    path:     /{id}/edit
    defaults: { _controller: "TGUdecBundle:Asesores:edit" }

asesores_update:
    path:     /{id}/update
    defaults: { _controller: "TGUdecBundle:Asesores:update" }
    requirements: { _method: post|put }

asesores_delete:
    path:     /{id}/delete
    defaults: { _controller: "TGUdecBundle:Asesores:delete" }
    requirements: { _method: post|delete }
