autores:
    path:     /
    defaults: { _controller: "TGUdecBundle:Autores:index" }
    
autores_proyecto:
    path:     /proyecto/{id}
    defaults: { _controller: "TGUdecBundle:Autores:proyecto" }

autores_show:
    path:     /{id}/show
    defaults: { _controller: "TGUdecBundle:Autores:show" }

autores_new:
    path:     /new
    defaults: { _controller: "TGUdecBundle:Autores:new" }

autores_create:
    path:     /create
    defaults: { _controller: "TGUdecBundle:Autores:create" }
    requirements: { _method: post }

autores_edit:
    path:     /{id}/edit
    defaults: { _controller: "TGUdecBundle:Autores:edit" }

autores_update:
    path:     /{id}/update
    defaults: { _controller: "TGUdecBundle:Autores:update" }
    requirements: { _method: post|put }

autores_delete:
    path:     /{id}/delete
    defaults: { _controller: "TGUdecBundle:Autores:delete" }
    requirements: { _method: post|delete }
