personas:
    path:     /
    defaults: { _controller: "TGUdecBundle:Personas:index" }

personas_show:
    path:     /{id}/show
    defaults: { _controller: "TGUdecBundle:Personas:show" }

personas_new:
    path:     /new
    defaults: { _controller: "TGUdecBundle:Personas:new" }

personas_create:
    path:     /create
    defaults: { _controller: "TGUdecBundle:Personas:create" }
    requirements: { _method: post }

personas_edit:
    path:     /{id}/edit
    defaults: { _controller: "TGUdecBundle:Personas:edit" }

personas_update:
    path:     /{id}/update
    defaults: { _controller: "TGUdecBundle:Personas:update" }
    requirements: { _method: post|put }

personas_delete:
    path:     /{id}/delete
    defaults: { _controller: "TGUdecBundle:Personas:delete" }
    requirements: { _method: post|delete }
