trabgrado:
    path:     /
    defaults: { _controller: "TGUdecBundle:Trabgrado:index" }

trabgrado_show:
    path:     /{id}/show
    defaults: { _controller: "TGUdecBundle:Trabgrado:show" }

trabgrado_new:
    path:     /new
    defaults: { _controller: "TGUdecBundle:Trabgrado:new" }

trabgrado_create:
    path:     /create
    defaults: { _controller: "TGUdecBundle:Trabgrado:create" }
    requirements: { _method: post }

trabgrado_edit:
    path:     /{id}/edit
    defaults: { _controller: "TGUdecBundle:Trabgrado:edit" }

trabgrado_update:
    path:     /{id}/update
    defaults: { _controller: "TGUdecBundle:Trabgrado:update" }
    requirements: { _method: post|put }

trabgrado_delete:
    path:     /{id}/delete
    defaults: { _controller: "TGUdecBundle:Trabgrado:delete" }
    requirements: { _method: post|delete }
