tg_udec_homepage:
    pattern:  /
    defaults: { _controller: TGUdecBundle:Default:index }
tg_udec_personas:
    resource: "@TGUdecBundle/Resources/config/routing/personas.yml"
    prefix:   /personas
tg_udec_sedes:
    resource: "@TGUdecBundle/Resources/config/routing/sedes.yml"
    prefix:   /sedes
tg_udec_programas:
    resource: "@TGUdecBundle/Resources/config/routing/programas.yml"
    prefix:   /programas
tg_udec_clasificacion:
    resource: "@TGUdecBundle/Resources/config/routing/clasificaciontg.yml"
    prefix:   /clasificacion
tg_udec_trabgrado:
    resource: "@TGUdecBundle/Resources/config/routing/trabgrado.yml"
    prefix:   /trabgrado
tg_udec_trabgrado_adjuntos:
    resource: "@TGUdecBundle/Resources/config/routing/archivostg.yml"
    prefix:   /adjuntos
tg_udec_trabgrado_adjuntos_file:
    pattern:   /file/{name}
    defaults: { _controller: TGUdecBundle:Default:file }
tg_udec_trabgrado_buscar_proyectos:
    pattern:   /buscarproyectos
    defaults: { _controller: TGUdecBundle:Default:buscarProyectos }